"""Changed nullable columns

Revision ID: 675570da9c70
Revises: 03b056d5254a
Create Date: 2025-11-07 12:24:27.955075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675570da9c70'
down_revision: Union[str, None] = '03b056d5254a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
