"""empty message

Revision ID: 714486235726
Revises: 67d02bc6630c
Create Date: 2025-11-08 15:53:31.224850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714486235726'
down_revision: Union[str, None] = '67d02bc6630c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_note_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'note_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tags_note_id_fkey', 'tags', 'notes', ['note_id'], ['id'])
    # ### end Alembic commands ###
