"""add nullable content to note

Revision ID: 8b5de0c414c9
Revises: 675570da9c70
Create Date: 2025-11-07 12:25:05.254430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5de0c414c9'
down_revision: Union[str, None] = '675570da9c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
