"""Add Note to Tags relationship

Revision ID: b4fc7a788fec
Revises: 8b5de0c414c9
Create Date: 2025-11-07 19:16:09.905718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fc7a788fec'
down_revision: Union[str, None] = '8b5de0c414c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
